/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  core_rulebook: [{type: 'autogenerated', dirName: '.'}],
  themes: [{type: 'autogenerated', dirName: '.'}],
  races: [{type: 'autogenerated', dirName: '.'}],
  classes: [{type: 'autogenerated', dirName: '.'}],
  skills: [{type: 'autogenerated', dirName: '.'}],
  equipments: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
